# Generated by Django 5.0.9 on 2024-11-14 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolio",
            old_name="students",
            new_name="student",
        ),
    ]
