# Generated by Django 5.0.9 on 2024-11-14 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("students", "0003_fileport_imageport_port_content_textport_videoport"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Port_Content",
            new_name="PortContent",
        ),
    ]
