# Generated by Django 5.0.9 on 2024-11-23 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_rename_fileport_file_rename_imageport_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                upload_to="files",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FileField(
                upload_to="images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
